project_id = "yxwspexyhhygghlzqoen"

[functions.stripe-onboard]
verify_jwt = false

[functions.stripe-status]
verify_jwt = false

[functions.stripe-dashboard]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.quote-trip]
verify_jwt = false
